development:
  adapter: postgresql
  encoding: unicode
  database: our_airports_dev
  pool: 5
  username: kbennett
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: our_airports_test
  pool: 5
  username: kbennett
  password:
