development:
  adapter: postgresql
  encoding: unicode
  database: our_airports
  pool: 5
  username: kbennett
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: our_airports
  pool: 5
  username: kbennett
  password:
